### ISSUE TITLE
Bootstrap template broken in develop

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1343]
@torinfo https://github.com/thexerteproject/xerteonlinetoolkits/commit/a349c8a682460a08a4041e8eef10c68232f77e77 This commit (I think) has broken the Bootstrap template. Seems to be to do with how the new initMedia function has been merged. The first issue is to do with the error event at the end of the function but when this is commented out it then throws up an error in popcorn.mediaconstructor.js file.

**Comment by FayCross** [comment]
After this has been fixed I will need to check whether the recent changes I made to audio players in BS still work (adding a transcript button to the end of the audio player)

**Comment by torinfo** [comment]
Apologies! That should not have been in there yet. I'll have a look.

**Comment by torinfo** [comment]
@FayCross That merge error should be fixed now.

**Comment by FayCross** [comment]
@torinfo still getting an error I'm afraid. Only on pages where there is video or audio though - e.g. https://xotbeta.dlearning.nl/preview.php?template_id=498#page2

**Comment by torinfo** [comment]
@FayCross Yes, lot's of things go wrong there. I'll have a look. Resizing does terrible things as well.
