### ISSUE TITLE
xampp set up fails with develop

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1358]
@torinfo I've been helping someone set up a new xampp install of Xerte today but it failed using develop (therefore also in 3.13?) Got the error 'Failed to execute query line 89 page2.php'. It worked ok when I downloaded 3.12 so don't think it was a xampp issue.

**Comment by torinfo** [comment]
@FayCross I think the whole zip is incorrect. Apologies. I'll have a look.

**Comment by torinfo** [comment]
@FayCross Yes, apologies, the whole zipfile was corrup AND there was a mistake in the database setup routine.

Fixed both.

**Comment by ronm123** [comment]
@torinfo @FayCross I'm reopening this after starting a new issue which I have now closed but the issue still exists after trying the fix committed as part of this.
I downloaded the current 3.13 and on page 2 got the following error: SQLSTATE[HY000] [1049] Unknown database 'xerte313'
I then copied and pasted the page2 code from this fix and still get the same error.
So it's a different error to what Fay reported but still an issue with installing 3.13 not working so would obviously be good to resolve that before Thursday.
