### ISSUE TITLE
Import pages/Merge showing as 503 service unavailable (latest develop)

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#641]
Hi all
in testing the audio slideshow problem that I just added as an issue separately I was trying to use the import/merge functionality to import a page from one LO to another on an installation using the latest develop code. This works fine for me on a couple of servers but with the very same code revision on one server/installation I'm getting a 503 service unavailable error in the console and the import dialogue therefore never appears. I notice this does a get ending with url's like /editor/importpages/import-choose.php?id=297&t=1498468697300 so could this be a firewall issue on this particular server or something else like a particular component or service not being installed/enabled?
Ron

**Comment by torinfo** [comment]
No php errors on the server?

**Comment by ronm123** [comment]
Hi @torinfo No nothing obvious as far as I can see but what does happen after clicking import/merge is that it kills the session and I have to refresh/login again. This install is using DB authentication. I'm going to turn debugging on and see if that reveals anything.

**Comment by torinfo** [comment]
@ronm123 Which version is this?

**Comment by ronm123** [comment]
@torinfo latest develop.
Turning on debugging hasn't revealed anything useful but on the very same server in a different folder/installation with the same code revision import works. Although some issues with import pages that I need to test and report separately similar to what I think Fay reported previously.

**Comment by torinfo** [comment]
@ronm123 Ok, but please make sure you're running the latest code. All Fay's issues should be fixed.

**Comment by ronm123** [comment]
@torinfo I've been testing further but still not finding why this installation doesn't work whereas others even on the same server do. A few quick questions:

1. Does the import functionality use js that may have been cached? That might explain the oddness I was getting with import on the install where it is working.

2. Could the import throw a wobbly on older projects that haven't been edited for sometime? The reason I ask this is because on the installation where import is working I was testing import of page from a very old project and despite the pages I selected it was importing different pages from earlier in the tree. However after opening that source project to inspect it and then re-testing import it started importing the correct pages.

3. On the installation where this is working I can open the import-choose link in a new window and it shows something like the following:
![image](https://user-images.githubusercontent.com/5167146/27550439-8dfd35e6-5a97-11e7-9a78-4c66bfda5a0c.png)

But on the install where this isn't working I get an error:
Setting up of database session failed.
Please notify server administrator.
I think that's only because clicking import is killing the session but does this give any other clues?

Cheers
Ron

**Comment by torinfo** [comment]
In an older version, import pages did open import-choose.php direectly, and was meant to redirect to the editor again. But if something went wrong, weird things would happen.

Now, import-choose.php is called as an ajax call (like it should). 

And yes probably a good idea to clear cache.

**Comment by ronm123** [comment]
unfortunately clearing cache hasn't resolved the issue but I'd been using force-refresh anyway so didn't expect it to. I'm going to do some further testing tomorrow.

**Comment by ronm123** [comment]
@torinfo ok this is curious. I downloaded a copy of my online installation that wasn't working to test locally via xampp. When I try to merge pages with the local copy I don't get the same 'service unavailable' error but right after import-choose there are some lines in the console showing tree.js loading then ending with a JSON error:
Uncaught SyntaxError: Unexpected token 
 in JSON at position 116855
    at JSON.parse (<anonymous>)
    at eval (eval at <anonymous> (jquery.min.js:3), <anonymous>:2:21)
    at eval (<anonymous>)
    at jquery.min.js:3
    at Function.globalEval (jquery.min.js:3)
    at jQuery.fn.init.domManip (jquery.min.js:4)
    at jQuery.fn.init.append (jquery.min.js:4)
    at jQuery.fn.init.<anonymous> (jquery.min.js:4)
    at Function.access (jquery.min.js:3)
    at jQuery.fn.init.html (jquery.min.js:4)

Given that merge tries to load a view of all existing projects etc could this be an issue with older projects or older database entries?

**Comment by torinfo** [comment]
So, it is project dependent. The json file you get back from import-choose.php is invalid. Would be interesting to get the json string.

The strange thing is that the json is produced exactly like the workspace, and the workspace does load.

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 is this still an issue with the latest code?

**Comment by ronm123** [comment]
Hi @JohnSmith-LT I think there have been 3 or 4 slightly different issues/solutions around import pages but yes I think they are all fixed.
1. a json issue which Fay also reported and Tom made changes to resolve
2. A moodle session related issue that was affecting one of my installs but changing the Moodle setting to use file system for sessions rather than database resolved that.
3. compatibility with older versions of PHP  2 separate lines of code changed
4. The speed of the tree loading that you and Tom have reolved

So I'll comment and close.
