### ISSUE TITLE
Problem with export in develop branch

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#656]
This seems to be over and above the issue with tsugi includes breaking the current develop but offline export creates a zip which looks to be not complete on my machine - i.e. the offline/models are created in a folder but the offline includes aren't being written to the index file and the index file being written has the filename index.php instead of .htm/.html

Anyone else seeing this?

**Comment by ronm123** [comment]
@JohnSmith-LT after your post I've just been testing and in my local copy of develop none of the export options work from projects based on the xot template. Decision and Site templates export but when I open the properties of an xot based project and try export none of the export buttons trigger an export. I don't see any browser console errors though. Not sure why you'rs is different to mine where you are getting a zip?

**Comment by JohnSmith-LT** [comment]
Oh sorry, i've reverted my develop branch export.php file to the one before all the xApi / Tsugi code was put in but it's only doing partial export, perhaps because it now interacts with that code in some way that i'm not seeing yet...

**Comment by torinfo** [comment]
That particular issue should be fixed now.

 - I need to cleanup the export code (sorry I missed that) The TSUGI code is still in there, and in the end I don't want it in there. It should NOT be necessary to export a TSUGI package at all, because that is not the purpose of LTI2.

**Comment by ronm123** [comment]
@torinfo @JohnSmith-LT Just testing export again after pulling down Tom's commits and the exports are still not working for me in the develop branch. Should this be fixed with those commits?
Does it work for you now John?

**Comment by JohnSmith-LT** [comment]
No I just tested and it doesn't work for me either @ronm123 but i've just pushed a fix

**Comment by ronm123** [comment]
@JohnSmith-LT that's cracked it! :-)
