### ISSUE TITLE
dashboard/workspace issues

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#769]
@torinfo as posted to the dev list here's a bit more detail re issues with your dashboard commit.

I've pulled down the commit, ran upgrade.php, can see the changes/options in management etc (including enable dashboard) but with xapi projects selected I'm not seeing any dashboard info in the workspace. I've cleared cache/offline files and I do see some css problems in the workspace but not seeing any dashboard image. Then again I'm not seeing any info at all in the middle panel even for a normal project that is public and not xapi. Errors when viewing workspace as follows:

Failed to load resource: the server responded with a status of 404 (Not Found)
screen_display.js:598 Setting up MainLayout...
3(index):1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.f.deserialize (xapicollection.min.js?version=unstable - installed from github:2)
    at onmessage (xapicollection.min.js?version=unstable - installed from github:2)
screen_display.js:721 Object#: {icon: "website_code/images/Icon_Page_null.gif", valid_children: Array(2)}decision: {icon: "website_code/images/Icon_Page_decision.gif", valid_children: Array(1)}folder: {icon: "website_code/images/Icon_Folder.gif", valid_children: Array(7)}mediainteractions: {icon: "website_code/images/Icon_Page_mediainteractions.gif", valid_children: Array(1)}multipersp: {icon: "website_code/images/Icon_Page_multipersp.gif", valid_children: Array(1)}nottingham: {icon: "website_code/images/Icon_Page_nottingham.gif", valid_children: Array(1)}recyclebin: {icon: "website_code/images/rb_empty.gif", valid_children: Array(7)}rss: {icon: "website_code/images/Icon_Page_rss.gif", valid_children: Array(1)}site: {icon: "website_code/images/Icon_Page_site.gif", valid_children: Array(1)}workspace: {icon: "website_code/images/folder_workspace.gif", valid_children: Array(7)}__proto__: Object
screen_display.js:722 Array(124)[0 … 99][100 … 123]length: 124__proto__: Array(0)
(index):2 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.getProjectInformation_stateChanged (template_management.js:670)
(index):1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.f.deserialize (xapicollection.min.js?version=unstable - installed from github:2)
    at onmessage (xapicollection.min.js?version=unstable - installed from github:2)

I'm also seeing css changes in the workspace that need fixing.
HTH
Ron

**Comment by ronm123** [comment]
@torinfo as discussed on the phone I've committed the following changes:
change loading order of nvd3, bootstrap and dashboard css files to remove impact on workspace
add left padding to dashboard header
removing max width for popover tooltips in dashboard
change width of embed code text box to percentage

But a few remaining issues for you to look at:

- [ ] date format in dashboard textboxes - currently showing mm/dd/yyyy and should be dd/mm/yyyy for GB
- [ ] the options div at the top of the dashboard doesn't fill the width if the results cause horizontal scrolling so the close dashboard button doesn't show when scrolled to the right. Couldn't find how best to resolve this.
- [ ] I had a look at setting a max-width for the table headers which does reduce the width but then spoils the display of the toggle to the right of those headings and also seeing the full titles could be more important than reducing horizontal scrolling

Ron

**Comment by torinfo** [comment]
Fixed the date issue (forgot to commit the i18n file to do this

I am not sure what to make of your second observation. What do you mean with 'if the results cause horizontal scrolling' ?

Can you send a screenshot please?

**Comment by ronm123** [comment]
@torinfo tested that - date issue fixed.
Screenshot added here. This might be exaggerated in terms of the number of pages because it's the page types demo but nonetheless it doesn't take too many pages to require horizontal scrolling and to exceed whatever is restricting the width of the div with the close dashboard button. Would be easy enough to set the button position to stay top right but I couldn't find where the width of the div it sits in was being constrained.
![image](https://user-images.githubusercontent.com/5167146/40794045-01c346f0-64f6-11e8-87c6-e3245c0c2f57.png)

**Comment by ronm123** [comment]
Note: I tried adding a scrolling screenshot to show the full effect but then edited and replaced that because it was duplicating elements as I scrolled. The replacement screenshot should suffice to show what I mean?

**Comment by torinfo** [comment]
Still not sure what the problem is. What I intended to accomplish is that the close button is (always) below the language selecotor (and thus, the 'title' bar or dashboard bar should not scroll, regardless of the number of pages in the LO.

Agree? Then at least we know what we're trying to accomplish.

**Comment by ronm123** [comment]
I haven't seen that. All I've seen is the close dashboard button top-right and not below the language selector. I think it looks good top right but as soon as the number of pages in the results is long enough to cause horizontal scrolling the close button stays at the right edge of the div it's sitting in and that div must have a fixed width set somewhere because it doesn't fill the width of the window when you scroll right e.g. 1st screenshot is default view:
![image](https://user-images.githubusercontent.com/5167146/40796186-2551557a-64fc-11e8-8203-941ba585faa0.png)
Second screenshot is scrolled right
![image](https://user-images.githubusercontent.com/5167146/40796225-454bc6b2-64fc-11e8-83da-6bcd9ec7c09a.png)
3rd screenshot shows right edge of div and button
![image](https://user-images.githubusercontent.com/5167146/40796250-62d68b22-64fc-11e8-81f3-60c1cf107c06.png)

**Comment by torinfo** [comment]
Got it. But you agree with me, it would be better to fixate the bar with the date and the cloase button?

**Comment by ronm123** [comment]
No not as it is now. Doesn't matter if the button was below or on the same line as the date as soon as you scroll right to see the latter pages you no longer see the close button. I think it would look better if the light grey div it sits in and the darker grey dive below that containing the LO title were to always fill the width of the window and then keep the close dashboard button top right e.g. on my 2nd screenshot above you would still see the two divs and the close button.

**Comment by ronm123** [comment]
Sorry I realised after sending that you probably mean the same as what I said more or less :-(
Also there's currently a slight mismatch between the light grey div and the div below it but that won't matter if both fill the width.
![image](https://user-images.githubusercontent.com/5167146/40797156-1a590fc0-64ff-11e8-8ed1-e1d3b51694fe.png)

**Comment by ronm123** [comment]
Tom - I realised another small problem too but not sure what the solution would be...
When you click one of the traffic light indicators the grey div (card-inverse) with start and completion time and duration appears with that info aligned left. e.g.
![image](https://user-images.githubusercontent.com/5167146/40797552-71cab758-6500-11e8-87ef-80eb452cd05d.png)
However if you click one of the traffic light indicators further right you no longer see the actional text unless you scroll back left e.g.
![image](https://user-images.githubusercontent.com/5167146/40797604-a78cd20e-6500-11e8-99a9-fd1145cc3327.png)
Is there a way that card-inverse could fix to the left of the browser window while scrolling right so that the text remains view-able?

**Comment by ronm123** [comment]
Sorry pasted the same screenshot twice. I corrected that but the email you get might be the original with two identical screenshots.

**Comment by torinfo** [comment]
@ronm123 

Improved fixation of the button/input bar and the title bar. It still does not work completey if the window is too narrow.

Also, with regards to your question on the card-inverse:
 - The when you click on one of the coloured boxes, you actually click on the row. So you can also click on a grey area on the row and it will display the same information. That information holds for the last attempt of the whole learning object, not only the interaction that you chose to click on. The popup show data the is valid for the specific interaction. I added duration to that popup.

 - When you properly finish the LO, i.e. you close the window, the information shown on card-inverse is the same as the results page (see screenshot)

 - I still have issues with the table layout. If an interaction with children (like the quiz) is expanded, the scrollbars appear in a position that I cannot fully understand. See green areas and green arrows in screenshot.

![dashboard](https://user-images.githubusercontent.com/5166596/40878786-4a49b750-6696-11e8-8755-a6059299c511.png)

**Comment by ronm123** [comment]
Hi Tom
The close dashboard button and bar seems much better now. However I’m missing something - I don’t get that results page view? I only get what was shown in my previous screenshots.

**Comment by torinfo** [comment]
Hi Ron,

That's because somehow the tracking of the LO was nog finished. Normally you should close the window in order to do that.

It is triggered by unload.

Sometimes I wished we had a better way. Perhaps I should add an optional parameter to add a stop LO button, or close button.

**Comment by torinfo** [comment]
Hmmm, yes that sounds about right, but I think I should change it, so it will get the results from the exited xapi staement rather than the completed xapi statement.

**Comment by ronm123** [comment]
Hi Tom yes I think that would be a good idea.
I also wonder about reducing the default "page timeout for completion" to say 3 rather than 5? I think that default of 5 trips a lot of people up when testing why completion isn't triggering?

**Comment by torinfo** [comment]
I did some experiments with the extra button/page, but regrettably, you cannot close a window/tab from javascript... But I'll what can be done

Also, 3 seconds for the default is fine by me.

**Comment by ronm123** [comment]
@torinfo @FayCross going to close this one :-) but open a new one with something related :-(
