### ISSUE TITLE
Math equations are not rendered poperly in Glossary

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#776]
Hi,
I have a math equation in glossary that is not displayed correctly
![image](https://user-images.githubusercontent.com/13013814/41189952-6eeaf5c0-6c08-11e8-9250-579f00ce44b9.png)

Thanks in advance for replying

**Comment by FayCross** [comment]
Thanks for letting us know about this - I've just committed a fix which will be included in our next release

**Comment by obgeneralao** [comment]
Hi,

Math equations inside the Glossary are rendered properly now however hovering those terms inside the different pages still showing the Math equations not displaying properly in the pop-up window

**Comment by FayCross** [comment]
Do you mean the tooltips that appear when you hover over a word?
This is working for me with the new code I committed last week:
![pi](https://user-images.githubusercontent.com/8926470/41654289-e1b6593e-7480-11e8-9b74-ef7e364eab52.png)

What do you see? Have you updated the xenith.js file?

**Comment by obgeneralao** [comment]
I reverted to the commit **aa84d23** and the tooltips show the  Math Equations rendered properly.

Thanks a lot
